# set paths of repository and storage folder (for files)

path_storage = "../data/"
dataset_name = "dataset10"

rule download_dataset:
    input: 
        script = "scripts/" + "download_dataset.py"
    output: path_storage + dataset_name + ".csv"
    shell: "python {input.script} {path_storage} {dataset_name}" # overwrite existing folder with '-o' flag

# execute all required rules
rule all:
    input: path_storage + dataset_name + ".csv"
