name: ML_Birds
dependencies:
  - python=3.9.19
  - numpy=1.26.4
  - matplotlib=3.9.1
  - scikit-learn=1.5.1
  - pandas=2.2.2
  - scipy=1.13.1
  - pip=24.0

  - pip:
    - tensorflow==2.16.1
    - tensorflow-probability[tf]
    - tensorflow_extra==1.0.2
    - tensorflow_io==0.37.1
    - librosa==0.10.2.post1
    - scikit-maad==1.4.2
    - notebook==7.2.1
    - tqdm==4.66.4
    - wandb==0.17.4
