name: ML_Birds
dependencies:
  - python=3.11.9
  - numpy=1.26.4
  - matplotlib=3.8.4
  - ipython=8.25.0
  - scikit-learn=1.5.0
  - pandas=2.2.2
  - scipy=1.13.1
  - pip=24.0

  - pip:
    - tensorflow==2.15.1
    - tensorflow-probability[tf]
    - tensorflow_extra==1.0.2
    - tensorflow_io==0.36.0
    - librosa==0.10.2.post1
    - scikit-maad==1.4.2
    - notebook
    - tqdm==4.66.4
